version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: money-api
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
    networks:
      - money_net

  postgres:
    image: postgres:16
    container_name: money-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: balance
      POSTGRES_DB: finbalance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - money_net

  redis:
    image: redis:7
    container_name: money-redis
    ports:
      - "6379:6379"
    networks:
      - money_net

networks:
  money_net:
    driver: bridge

volumes:
  pgdata:
